version: '3.9'

services:
  builder:
    image: docker:27-cli
    container_name: institute-listing-image-builder
    env_file:
      - .env   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    working_dir: /app
    environment:
      IMAGE_TAG: ${IMAGE_TAG}
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
    networks:
      - institute-listing-network
    command: [ "sh", "./build-push.sh" ]
    restart: "no"

  app:
    image: abishek1022/institute-listing:${IMAGE_TAG}
    container_name: institute-listing-app
    env_file:
      - .env
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - institute-listing-network
    depends_on:
      postgresql-container:
        condition: service_healthy
    command: >
      sh -c "
      MAX_RETRIES=3;
      RETRY_COUNT=0;

      until nc -z postgresql-container 5432; do
        RETRY_COUNT=$((RETRY_COUNT+1));
        echo \"Waiting for PostgreSQL... attempt ${RETRY_COUNT}/${MAX_RETRIES}\";

        if [ ${RETRY_COUNT} -ge ${MAX_RETRIES} ]; then
          echo \"PostgreSQL not available after ${MAX_RETRIES} attempts. Exiting.\";
          exit 1;
        fi;

        sleep 10;
      done;
      echo \"PostgreSQL is up. Starting Spring Boot...\";
      exec java -jar /app/institute-listing.jar
      "

  postgresql-container:
    image: postgres:14.1-alpine
    container_name: postgresql-container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - institute_listing_volume:/var/lib/postgresql/data
    networks:
      - institute-listing-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
networks:
  institute-listing-network:
    driver: bridge

volumes:
  institute_listing_volume:
