spring.application.name=listing

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

#load .evn properties
spring.config.import=optional:file:.env[.properties]

# Database connection properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#Google creds
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}

#spring max reties
retry.maxAttempts=${RETRY_MAX_ATTEMPTS}

#gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.api.model=${GEMINI_API_MODEL}