name: Institute Listing API CI/CD pipeline

on:
  push:
    branches:
      - ci-cd-pipeline
    paths:
      - src/**
      - Dockerfile
      - docker-compose.yml
      - build-push.sh
      - .github/workflows/institute-listing-ci-cd.yml

jobs:
  compile:
    runs-on: self-hosted
    name: Compile Project
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - run: |
          chmod +x gradlew
          ./gradlew clean assemble

  unit-tests:
    runs-on: self-hosted
    name: Unit Test Pipeline
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - run: |
          chmod +x gradlew
          ./gradlew clean test

  build:
    runs-on: self-hosted
    name: Build Institute Listing API
    needs: [compile, unit-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - run: |
          chmod +x gradlew
          ./gradlew assemble

  build-image:
    name: Build And Push Docker Image
    runs-on: self-hosted
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat <<EOF > .env
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DB_USERNAME=${{ secrets.POSTGRES_USER }}
          DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          DB_URL=${{ secrets.DB_URL }}
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_SCOPE=${{ secrets.GOOGLE_SCOPE }}
          GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
          RETRY_MAX_ATTEMPTS=${{ secrets.RETRY_MAX_ATTEMPTS }}
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          GEMINI_API_MODEL=${{ secrets.GEMINI_API_MODEL }}
          SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}
          EOF

      - run: chmod +x build-push.sh
      - run: docker compose run --rm -T builder

  build-postgresql-container:
    name: Run PostgreSQL container
    runs-on: self-hosted
    needs: [build-image]
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          mkdir -p src/main/resources
          cat <<EOF > src/main/resources/.env
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          EOF

      - name: Start PostgreSQL
        run: docker compose up -d  postgresql-container

  deploy:
    name: Deploy Institute Listing API
    runs-on: self-hosted
    needs: [build-image, build-postgresql-container]
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        run: |
          ssh -oStrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          mkdir -p ci-cd
          cd ci-cd
          docker compose pull
          docker compose up -d  institute-listing-app
          EOF
